@startuml
actor User

User -> NetworkApp: main()
activate NetworkApp

NetworkApp -> "feed:NewsFeed": new NewsFeed()


NetworkApp -> "m1:MessagePost": new MessagePost("Arne", "Hello, world!")
NetworkApp -> "feed:NewsFeed": addMessagePost()

NetworkApp -> "m2:MessagePost": new MessagePost("Leif", "Fun day out today!")

NetworkApp -> "feed:NewsFeed": addMessagePost()

NetworkApp -> "p1:PhotoPost": new PhotoPost("Jon", "bilde.jpg", "Sunset")
NetworkApp -> "feed:NewsFeed": addPhotoPost()

NetworkApp -> "p2:PhotoPost" : new PhotoPost("Lise", "mountain.jpg", "Hike")
NetworkApp -> "feed:NewsFeed": addPhotoPost()

NetworkApp -> "feed:NewsFeed": show()
activate "feed:NewsFeed"
"feed:NewsFeed" -> "m1:MessagePost": display()

"feed:NewsFeed" -> "m2:MessagePost": display()

"feed:NewsFeed" -> "p1:PhotoPost": display()

"feed:NewsFeed" -> "p2:PhotoPost": display()

deactivate "feed:NewsFeed"

deactivate NetworkApp
@enduml